[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = ["openjdk_21", "maven"]

[phases.build]
nixPkgs = ["openjdk_21", "maven"]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -jar target/*.jar"

[variables]
SPRING_PROFILES_ACTIVE = "production"
SERVER_PORT = "8080"
